spring.application.name=reactive-project-rest
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/projects
spring.r2dbc.username=postgres
spring.r2dbc.password=student
logging.level.root=INFO
logging.level.com.project=DEBUG
logging.level.org.springframework.r2dbc=DEBUG